# Display help text in the console using Write-Host
Write-Host "===================================================="
Write-Host "HELP: PowerShell Setup, Install, and Delete Commands"
Write-Host "===================================================="
Write-Host ""
Write-Host "setup (initializes the tool)"
Write-Host "===================================================="
Write-Host 'initializes the tool'
Write-Host ""
Write-Host "run 'elx setup' the first time you run elx"
Write-Host ''
Write-Host ""
Write-Host "install (get the moduls of this tool)"
Write-Host "===================================================="
Write-Host "Use Install-Module to install modules from the elx Gallery."
Write-Host ""
Write-Host "Example - Install the gito module:"
Write-Host "- 'elx install'"
Write-Host "- then chose gito"
Write-Host "- press enter"
Write-Host ""
Write-Host "--delete (Delete this tool)"
Write-Host "===================================================="
Write-Host ""
Write-Host "Removes this tool form you pc this command can not be returnd"
Write-Host ""
Write-Host "[befehl <z.B. gito>] --uninstall (Modules or Packages)"
Write-Host "===================================================="
Write-Host 'Use Uninstall-Module to uninstall elx modules.'
Write-Host ""
Write-Host "Example - Uninstall the gito module:"
Write-Host 'gito --uninstall'
